import '../entities/mentoring_note.dart';
import '../repositories/mentoring_repository.dart';

/// Use Case: Save mentoring note
class SaveMentoringNoteUseCase {
  final MentoringRepository repository;

  SaveMentoringNoteUseCase(this.repository);

  /// Save a new mentoring note with validation
  Future<void> call({
    required String santriId,
    required String santriName,
    required String mentorId,
    required String mentorName,
    required String note,
    required String category,
  }) async {
    // Validation
    if (santriId.trim().isEmpty) {
      throw ArgumentError('Santri ID cannot be empty');
    }

    if (mentorId.trim().isEmpty) {
      throw ArgumentError('Mentor ID cannot be empty');
    }

    if (note.trim().isEmpty) {
      throw ArgumentError('Note cannot be empty');
    }

    if (category.trim().isEmpty) {
      throw ArgumentError('Category cannot be empty');
    }

    // Validate category
    final validCategories = ['akademik', 'spiritual', 'sosial', 'lainnya'];
    if (!validCategories.contains(category.toLowerCase())) {
      throw ArgumentError(
        'Invalid category. Must be one of: ${validCategories.join(", ")}',
      );
    }

    // Create mentoring note
    final mentoringNote = MentoringNote(
      id: '', // Auto-generated by Firestore
      santriId: santriId,
      santriName: santriName,
      mentorId: mentorId,
      mentorName: mentorName,
      note: note.trim(),
      category: category.toLowerCase(),
      createdAt: DateTime.now(),
    );

    // Save to repository
    await repository.saveMentoringNote(mentoringNote);
  }
}
