import '../entities/violation.dart';
import '../repositories/violation_repository.dart';

/// Use Case: Record a violation
class RecordViolationUseCase {
  final ViolationRepository repository;

  RecordViolationUseCase(this.repository);

  /// Record a new violation with validation
  Future<void> call({
    required String userId,
    required String userDisplayName,
    required int kelompokId,
    required String ruleId,
    required String ruleName,
    required String category,
    required String recordedBy,
    String? timeDetail,
  }) async {
    // Validation
    if (userId.trim().isEmpty) {
      throw ArgumentError('User ID cannot be empty');
    }

    if (ruleId.trim().isEmpty) {
      throw ArgumentError('Rule ID cannot be empty');
    }

    if (recordedBy.trim().isEmpty) {
      throw ArgumentError('Recorded by cannot be empty');
    }

    if (kelompokId < 1) {
      throw ArgumentError('Invalid kelompok ID');
    }

    // Create violation case
    final violation = ViolationCase(
      id: '', // Will be auto-generated by Firestore
      userId: userId,
      userDisplayName: userDisplayName,
      kelompokId: kelompokId,
      ruleId: ruleId,
      ruleName: ruleName,
      category: category,
      timeDetail: timeDetail,
      recordedAt: DateTime.now(),
      recordedBy: recordedBy,
    );

    // Save to repository
    await repository.recordViolation(violation);
  }
}
