// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        // Use web config for Linux desktop
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALAwhfIGOb5i7ls65-4t7t_Qqrl_VpA7Q',
    appId: '1:733581949032:web:dfe3bf0a8cbdab236123dd',
    messagingSenderId: '733581949032',
    projectId: 'recap-bq',
    authDomain: 'recap-bq.firebaseapp.com',
    storageBucket: 'recap-bq.firebasestorage.app',
    measurementId: 'G-NPPVK772DQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxr8VKk9m2_CZehvr7Y0yyrwd6uQCbz-s',
    appId: '1:733581949032:android:b7f14f9b9c5e1b356123dd',
    messagingSenderId: '733581949032',
    projectId: 'recap-bq',
    storageBucket: 'recap-bq.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBSP_E84cGtFddpGs3SZHaMwpHU9Z9rFY',
    appId: '1:733581949032:ios:843a358514d5aed86123dd',
    messagingSenderId: '733581949032',
    projectId: 'recap-bq',
    storageBucket: 'recap-bq.firebasestorage.app',
    androidClientId:
        '733581949032-q0ub7ejjb1ikp40eqrqalpdofbsirsif.apps.googleusercontent.com',
    iosClientId:
        '733581949032-siq9qnki3bv8bg29f3ild9qirn7brb91.apps.googleusercontent.com',
    iosBundleId: 'com.baitulqowwam.siqowwam',
  );
}
